import Head from "next/head";
import Image from "next/image";
export const getStaticProps = async () => {
  const fetched_data = await fetch("http://localhost:8000/api");
  const json_data = await fetched_data.json();
  return {
    props: { products: json_data },
  };
};
export default function Home({ products }) {
  return (
    <div>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {products.map((product) => {
        return (
          <div key={product.id}>
            {product.name}
            {product.price}
            {product.created_at}
          </div>
        );
      })}
    </div>
  );
}
