# Generated by Django 3.2 on 2022-08-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='zip',
            field=models.IntegerField(max_length=5),
        ),
    ]
