# Generated by Django 3.2 on 2022-08-06 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_quote_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='zip',
            field=models.CharField(max_length=6, validators=[django.core.validators.MaxLengthValidator(6), django.core.validators.MinLengthValidator(6)]),
        ),
    ]
