# Generated by Django 3.2 on 2022-08-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_quote_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='effective_date',
            field=models.DateField(auto_now=True),
        ),
    ]
