# Generated by Django 3.2 on 2022-08-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_quote_effective_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='line_1',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='line_2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
