# Generated by Django 3.2 on 2022-08-07 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220807_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='address_line_2',
        ),
    ]
