# Generated by Django 3.2 on 2022-08-07 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_quote_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='zip',
            field=models.CharField(max_length=5, validators=[django.core.validators.MaxLengthValidator(5), django.core.validators.MinLengthValidator(5)]),
        ),
    ]
