# Generated by Django 4.1 on 2022-08-05 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('mobile_number', models.BigIntegerField(blank=True, null=True)),
                ('office_number', models.BigIntegerField(blank=True, null=True)),
                ('home_number', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=25, null=True)),
                ('team_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ManyToManyField(to='base.profile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.team')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='team',
            field=models.ManyToManyField(to='base.team'),
        ),
        migrations.CreateModel(
            name='MeetingsAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('member', models.ManyToManyField(blank=True, related_name='members', to='base.profile')),
                ('member_primary', models.ManyToManyField(blank=True, related_name='member_primary', to='base.profile')),
                ('member_secondary', models.ManyToManyField(blank=True, related_name='member_secondary', to='base.profile')),
                ('member_teritary', models.ManyToManyField(blank=True, related_name='member_teritary', to='base.profile')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_team_id', to='base.team')),
                ('team_lead_primary', models.ManyToManyField(blank=True, related_name='team_leader_primary', to='base.profile')),
                ('team_lead_secondary', models.ManyToManyField(blank=True, related_name='team_leader_secondary', to='base.profile')),
                ('team_manager', models.ManyToManyField(blank=True, related_name='team_manager', to='base.profile')),
            ],
        ),
    ]
