# Generated by Django 4.1 on 2022-08-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingsassigned',
            name='member_secondary',
            field=models.ManyToManyField(blank=True, default=None, related_name='member_secondary', to='base.profile'),
        ),
    ]
