# Generated by Django 4.1 on 2022-08-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingsassigned',
            name='date2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
