# Generated by Django 4.1 on 2022-08-05 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedrole',
            old_name='team_id',
            new_name='team_id_wow',
        ),
    ]
