# Generated by Django 4.1 on 2022-08-04 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='contact_number_1',
            new_name='home_number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='contact_number_2',
            new_name='mobile_number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='contact_number_3',
            new_name='office_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='team_member',
            field=models.ManyToManyField(to='base.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_lead_primary',
            field=models.ManyToManyField(related_name='team_leader_secondary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='team_manager',
            field=models.ManyToManyField(related_name='team_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='team_members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
