# Generated by Django 4.1 on 2022-08-05 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedrole',
            name='team',
        ),
    ]
