# Generated by Django 4.1 on 2022-08-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_meetingsassigned_member_secondary'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=models.CharField(default=' ', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetingsassigned',
            name='member_secondary',
            field=models.ManyToManyField(blank=True, default='', related_name='member_secondary', to='base.profile'),
        ),
    ]
