# Generated by Django 4.1 on 2022-08-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_meetingsassigned_member_secondary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingsassigned',
            name='member_secondary',
            field=models.ManyToManyField(blank=True, default='', related_name='member_secondary', to='base.profile'),
        ),
    ]
