# Generated by Django 4.1 on 2022-08-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_meetingsassigned_date2'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingsassigned',
            name='end_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingsassigned',
            name='start_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
