# Generated by Django 4.1 on 2022-08-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_assignedrole_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedrole',
            name='members',
        ),
        migrations.AddField(
            model_name='assignedrole',
            name='members',
            field=models.ManyToManyField(related_name='team_members', to='base.teammember'),
        ),
    ]
