# Generated by Django 4.1 on 2022-08-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_contact_number_1_profile_home_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
