# Generated by Django 4.1 on 2022-08-05 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_team_id_wow_assignedrole_team_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('time', models.TimeField(blank=True)),
                ('date_time', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingsAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_meeting', to='base.meetings')),
                ('roles', models.ManyToManyField(blank=True, to='base.assignedrole')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_team_id', to='base.team')),
            ],
        ),
    ]
