# Generated by Django 4.1 on 2022-08-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_assignedrole_members_assignedrole_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedrole',
            name='members',
            field=models.ManyToManyField(related_name='team_members', to='base.profile'),
        ),
    ]
