# Generated by Django 4.1 on 2022-08-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_assignedrole_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingsassigned',
            old_name='time',
            new_name='end_time',
        ),
        migrations.RemoveField(
            model_name='meetingsassigned',
            name='date_time',
        ),
        migrations.AddField(
            model_name='meetingsassigned',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
