# Generated by Django 4.1 on 2022-08-04 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_team_team_lead_secondary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_members',
        ),
        migrations.AddField(
            model_name='team',
            name='member_primary',
            field=models.ManyToManyField(blank=True, related_name='memberer_primary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='member_secondary',
            field=models.ManyToManyField(blank=True, related_name='memberer_secondary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='member_teritary',
            field=models.ManyToManyField(blank=True, related_name='memberer_teritary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='other_team_members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_lead_primary',
            field=models.ManyToManyField(blank=True, related_name='team_leader_primary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_lead_secondary',
            field=models.ManyToManyField(blank=True, related_name='team_leader_secondary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_manager',
            field=models.ManyToManyField(blank=True, related_name='team_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
