# Generated by Django 4.1 on 2022-08-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_meetingsassigned_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingsassigned',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingsassigned',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingsassigned',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
