# Generated by Django 4.1 on 2022-08-04 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_remove_team_team_members_team_member_primary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='other_team_members',
        ),
        migrations.AddField(
            model_name='team',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_primary',
            field=models.ManyToManyField(blank=True, related_name='member_primary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_secondary',
            field=models.ManyToManyField(blank=True, related_name='member_secondary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_teritary',
            field=models.ManyToManyField(blank=True, related_name='member_teritary', to=settings.AUTH_USER_MODEL),
        ),
    ]
