# Generated by Django 4.1 on 2022-08-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_time_meetingsassigned_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='team_id',
            new_name='team',
        ),
    ]
