# Generated by Django 4.1 on 2022-08-04 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_team_member_profile_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_members',
        ),
    ]
