# Generated by Django 4.1 on 2022-08-04 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0008_remove_team_team_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('teritary', 'teritary')], max_length=60)),
                ('team_id', models.ManyToManyField(to='base.team')),
                ('user_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
