const colors = require("tailwindcss/colors");
module.exports = {
  mode: "jit",
  purge: ["./pages/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  darkMode: false, // or 'media' or 'class'
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      black: colors.black,
      white: colors.white,
      gray: colors.coolGray,
      red: colors.red,
      yellow: colors.amber,
      blue: colors.blue,
      green: colors.green,
      teal: colors.teal,
      emerald: colors.emerald,
      cyan: colors.cyan,
      upworkgreen: {
        light: "#14a800",
        dark: "#45793e",
        verified: "#3c8224",
        copylink: "#6cc85f",
        trail: "#95df00",
        stroke: "#dbf0a3",
        form: "#1C4355",
        bar: "#95DE01",
        button: "#14A901",
      },
    },
    fontSize: {
      xxs: ".70rem",
      xs: ".75rem",
      sm: ".875rem",
      tiny: ".875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.875rem",
      "4xl": "2.25rem",
      "5xl": "3rem",
      "6xl": "4rem",
      "7xl": "5rem",
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
