import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import ComponentIndex from '../components/ComponentIndex'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Your Car</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href="/car-logo-dark.png" />
      </Head>

      <ComponentIndex />
    </div>
  )
}

export default Home
