# Generated by Django 3.2.8 on 2021-11-20 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20211031_2224'),
        ('chat', '0003_chatmessage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user1', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='accounts.profile')),
                ('user2', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='accounts.profile')),
            ],
        ),
    ]
