# Generated by Django 3.2.8 on 2021-11-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatroom_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='user2',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user_id_1',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user_id_2',
            field=models.CharField(default='2', max_length=100),
        ),
    ]
