# Generated by Django 3.2.8 on 2021-11-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20211121_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='messages',
            field=models.ManyToManyField(blank=True, to='chat.ChatMessage'),
        ),
    ]
