# Generated by Django 3.2.8 on 2021-11-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatroom_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='profile',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user_id',
            field=models.CharField(blank=True, default='1', max_length=100),
        ),
    ]
