# Generated by Django 3.2.5 on 2021-07-25 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_useraccount_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(blank=True, choices=[('Client', 'Client'), ('Freelancer', 'Freelancer')], max_length=25, null=True)),
                ('dp', models.ImageField(upload_to='profile_pic')),
                ('verified', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, null=True)),
                ('total_earnings', models.FloatField(blank=True, null=True)),
                ('total_jobs', models.IntegerField(blank=True)),
                ('video_intro_link', models.CharField(blank=True, max_length=255, null=True)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('languages', models.ManyToManyField(to='accounts.Languages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
