# Generated by Django 3.2.5 on 2021-07-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_languages_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
            ],
        ),
    ]
