# Generated by Django 3.2.5 on 2021-07-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_freelancer_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(to='accounts.Freelancer_skills'),
        ),
    ]
