# Generated by Django 3.1 on 2021-10-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20211019_1353'),
        ('accounts', '0013_auto_20211019_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.ManyToManyField(to='base.Skill'),
        ),
    ]
