# Generated by Django 3.1 on 2021-10-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_post_profile'),
        ('accounts', '0014_auto_20211019_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=models.ManyToManyField(blank=True, to='accounts.Languages'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=models.ManyToManyField(blank=True, to='base.Skill'),
        ),
    ]
