# Generated by Django 3.1 on 2021-10-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20211026_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_jobs',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
