# Generated by Django 4.2.3 on 2023-08-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="title_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
