# Generated by Django 3.2.5 on 2021-07-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Web design', 'Web design')], max_length=255, null=True)),
                ('weekly_length', models.CharField(choices=[('Less than 30 hours', 'Less than 30 hours'), ('More than 30 hours', 'Less than 30 hours')], max_length=255, null=True)),
                ('total_length', models.CharField(blank=True, choices=[('Less than a month', 'Less than a month'), ('More than a month', 'More than a month'), ('Six months', 'Six months')], max_length=255)),
                ('date_createad', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
