# Generated by Django 3.2.5 on 2021-07-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='skill',
            field=models.ManyToManyField(blank=True, to='base.Skill'),
        ),
    ]
