# Generated by Django 3.2.5 on 2021-07-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_post_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='skill',
            field=models.ManyToManyField(to='base.Skill'),
        ),
    ]
