# Generated by Django 3.2.5 on 2021-07-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_post_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='freelancer_type',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='from_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='pay_type',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Fixed-price', 'Fixed-price')], max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='to_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
