# Generated by Django 3.2.5 on 2021-07-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210723_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fixed_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
