# Generated by Django 3.2.5 on 2021-07-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_post_fixed_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_createad',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='post',
            name='weekly_length',
            field=models.CharField(choices=[('Less than 30 hours', 'Less than 30 hours'), ('More than 30 hours', 'More than 30 hours')], max_length=255, null=True),
        ),
    ]
