# Generated by Django 3.2.5 on 2021-08-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210723_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='weekly_length',
            field=models.CharField(blank=True, choices=[('Less than 30 hours', 'Less than 30 hours'), ('More than 30 hours', 'More than 30 hours')], max_length=255, null=True),
        ),
    ]
