# Generated by Django 3.2.5 on 2021-08-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_post_weekly_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='total_length',
            field=models.CharField(blank=True, choices=[('Less than a month', 'Less than a month'), ('More than a month', 'More than a month'), ('Six months', 'Six months')], max_length=255, null=True),
        ),
    ]
